#ifndef __CONSTANTES_H__
#define __CONSTANTES_H__

#define VACIO ' '
#define LINGUINI 'L'
#define MESAS 'T'
#define COCINA 'C'
#define CHARCOS 'H'
#define MOPA 'O'
#define MONEDAS 'M'
#define PATINES 'P'
#define CANT_PATINES_INICIAL 0
#define CANT_BANDEJA_INICIAL 0
#define CANT_PEDIDOS_INICIAL 0
#define CANT_MOPA 1
#define CANT_MONEDAS 8
#define CANT_PATINES 5
#define CANT_CHARCOS 5
#define CANT_MESAS_INDIVIDUALES 6
#define CANT_MESAS_GRUPALES 4
#define CANT_LUGARES_INDIVIDUAL 1
#define CANT_COMENSALES_INICIAL 0
#define PACIENCIA_INICIAL 0 
#define GANADO 1
#define PERDIDO -1
#define SIGUE_JUGANDO 0
#define ARRIBA 'W'
#define ABAJO 'S'
#define DERECHA 'D'
#define IZQUIERDA 'A'
#define AGARRA_SUELTA_MOPA 'O'
#define NO_HAY_CHARCO -1
#define CUCARACHAS 'U'
#define COMENSALES 'X'
#define MILANESA_NAPOLITANA 'M'
#define HAMBURGUESA 'H'
#define PARRILLA 'P'
#define RATATOUILLE 'R'
#define PEDIDO_NAPOLITANA 1
#define PEDIDO_HAMBURGUESA 2
#define PEDIDO_PARRILLA 3
#define PEDIDO_RATATOUILLE 4 
#define TIEMPO_PREPARACION_NAPOLITANA 30 
#define TIEMPO_PREPARACION_HAMBURGUESA 15
#define TIEMPO_PREPARACION_PARRILLA 20
#define TIEMPO_PREPARACION_RATATOUILLE 25 
#define MESA_GRUPAL_PAGA 20000
#define MESA_INDIVIDUAL_PAGA 5000
#define TODAVIA_NO_PAGO 0
#define TOMAR_PEDIDO 'T'
#define ACTIVAR_PATINES 'P'
#define NO_AGARRA_MOPA_CON_PATINES 'N'
#define DINERO_MONEDA_EXTRA 1000

#endif /* __CONSTANTES_H__ */
